    - name: Install MySQL
      yum:
        name: "{{ item }}"
        state: latest
      loop:
         - "{{repo}}"
         - mysql-community-devel
         - mysql-community-server
         - MySQL-python

    - name: Copy .my.cnf file with root password credentials
      template:
        src: templates/.my.cnf
        dest: /root/.my.cnf
        owner: root
        mode: 0600
        backup: yes

    - name: Start the MySQL service
      systemd:
        name: mysqld 
        state: restarted 
        enabled: yes

#    - name: get root password
#      shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
#      register: root_password
    
#    - name: update expired root user password
#      command: mysql --user root --password={{ root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"

#    - name: Removes anonymous user account for localhost
#      mysql_user:
#        name: ''
#        host: localhost
#        state: absent

    - name: Create mysql user for mysql
      command: mysql --user root --password={{ mysql_root_password }} --execute="CREATE USER 'newuser3'@'localhost' IDENTIFIED BY 'QWEasd@123';"

#      mysql_user: 
#        login_user: root
#        login_password: "{{ mysql_root_password }}"
#        name: "{{ item.name }}"
#        password: "{{ item.password }}"
#        priv: '*.*:ALL,GRANT'
#        state: present
#        host: '%' 
#      loop:
#         - { name: 'testuser1', password: 'QWEasd@123' }
#         - { name: 'testuser2', password: 'QWEasd@123' }
#         - { name: 'testuser3', password: 'QWEasd@123' }

#    - name: Update mysql root password for all root accounts
#      mysql_user: 
#        name: root 
#        host: "{{ item }}" 
#        password: "{{ mysql_root_password }}"
#      loop:
#         - 127.0.0.1
#         - ::1
#         - localhost

    - name: Open firewall for port 3306
      firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
      notify:
        - restart firewall
